# Site settings
title: Codejock
email: burton.wynne.developer@gmail.com
url: https://burtonwynne.github.io/blogs/
description: "Hi, My name is Burton and I'm a developer.  I've been in the field for about 12 years and I like to program in java.  My hobbies are muay thai, karate, working out, watching Game of Thrones and learning new things!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: https://burtonwynne.github.io/blogs/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/codejock
  #- title: facebook
  #  url:
  #- title: stack-overflow
   # url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket
  #  url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/burtonwynne

# Build settings
markdown: kramdown
permalink: pretty
